// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Infraestructura.AccesoDatos;

public partial class Asistencias
{
    public int IdAsistencia { get; set; }

    public int EmpleadoId { get; set; }

    public DateOnly Fecha { get; set; }

    public TimeOnly? HoraEntrada { get; set; }

    public TimeOnly? HoraSalida { get; set; }

    public bool? Estado { get; set; }

    public TimeOnly? HoraInicioAlmuerzo { get; set; }

    public TimeOnly? HoaFinAlmuerzo { get; set; }
    [JsonIgnore]
    public virtual Empleados Empleado { get; set; }
}