// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Infraestructura.AccesoDatos;

public partial class Bonificaciones
{
    public int IdBonificacion { get; set; }

    public int EmpleadoId { get; set; }

    public string Tipo { get; set; }

    public string Descripcion { get; set; }

    public decimal Monto { get; set; }

    public DateOnly Fecha { get; set; }

    public bool? Estado { get; set; }
    [JsonIgnore]
    public virtual Empleados Empleado { get; set; }
}