// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Infraestructura.AccesoDatos;

public partial class ContratosTipo
{
    public int IdTipo { get; set; }

    public string Jornada { get; set; }

    public string Nombre { get; set; }

    public int? HorasJornada { get; set; } //?

    [JsonIgnore]
    public virtual ICollection<Contratos> Contratos { get; set; } = new List<Contratos>();
}