// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Infraestructura.AccesoDatos;

public partial class EmpleadosVacacionesTotales
{
    public int EmpleadoId { get; set; }

    public int DiasOtorgados { get; set; }


    public int DiasUsados { get; set; } // Total de días de vacaciones que el empleado ha utilizado
    [JsonIgnore]

    public virtual Empleados Empleado { get; set; }

    public int CalcularDiasOtorgados()
    {
        if (Empleado == null)
            throw new InvalidOperationException("Empleado no cargado en VacacionesTotales.");

        int años = (int)((DateTime.Now.Date - Empleado.FechaIngreso.ToDateTime(TimeOnly.MinValue)).TotalDays / 365);
        return años * 15;
    }

    public int CalcularDiasDisponibles()
    {
        int otorgados = CalcularDiasOtorgados();
        int disponibles = otorgados - DiasUsados;
        return Math.Min(disponibles, 30); // Solo se pueden usar 30 como máximo
    }
}