// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infraestructura.AccesoDatos;

public partial class EmpleadosVacacionesTotales
{
    public int EmpleadoId { get; set; }

    public int DiasOtorgados { get; set; } // Total de días de vacaciones otorgados al empleado

    public int DiasUsados { get; set; } // Total de días de vacaciones que el empleado ha utilizado

    public virtual Empleados Empleado { get; set; }
}