// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infraestructura.AccesoDatos;

public partial class Licencias
{
    public int IdLicencia { get; set; }

    public string Nombre { get; set; }

    public bool Remunerable { get; set; }

    public virtual ICollection<Inasistencias> Inasistencias { get; set; } = new List<Inasistencias>();
}