// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Infraestructura.AccesoDatos;

public partial class Nominas
{
    public int IdNomina { get; set; }

    public int EmpleadoId { get; set; }

    public byte Mes { get; set; }

    public short Anio { get; set; }

    public decimal SalarioBase { get; set; }

    public decimal Bonificaciones { get; set; }

    public decimal Descuentos { get; set; }

    public DateOnly FechaEmision { get; set; }
<<<<<<< HEAD
=======

    public bool? Estado { get; set; }
>>>>>>> 38fd4c0964f95e1de6b720f61748a98a7aed1308
    [JsonIgnore]
    public virtual Empleados Empleado { get; set; }
}