// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Infraestructura.AccesoDatos;

public partial class NominaDBContext : DbContext
{
    public NominaDBContext()
    {
    }

    public NominaDBContext(DbContextOptions<NominaDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AprobacionVacaciones> AprobacionVacaciones { get; set; }

    public virtual DbSet<Asistencias> Asistencias { get; set; }

    public virtual DbSet<Bonificaciones> Bonificaciones { get; set; }

    public virtual DbSet<Contratos> Contratos { get; set; }

    public virtual DbSet<ContratosTipo> ContratosTipo { get; set; }

    public virtual DbSet<Descuentos> Descuentos { get; set; }

    public virtual DbSet<Empleados> Empleados { get; set; }

    public virtual DbSet<EmpleadosVacacionesTotales> EmpleadosVacacionesTotales { get; set; }

    public virtual DbSet<Inasistencias> Inasistencias { get; set; }

    public virtual DbSet<Licencias> Licencias { get; set; }

    public virtual DbSet<Nominas> Nominas { get; set; }

    public virtual DbSet<Parametros> Parametros { get; set; }

    public virtual DbSet<Puestos> Puestos { get; set; }

    public virtual DbSet<SolicitudVacaciones> SolicitudVacaciones { get; set; }

    public virtual DbSet<Usuarios> Usuarios { get; set; }

   /* protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=(localdb)\\leo;Initial Catalog=ModuloNomina;Integrated Security=True;Encrypt=True");*/

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AprobacionVacaciones>(entity =>
        {
            entity.HasKey(e => e.IdAprobacion).HasName("PK__Aprobaci__3E675ACB854E4414");

            entity.Property(e => e.FechaAprobacion).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.UsuarioAprobador).HasMaxLength(100);

            entity.HasOne(d => d.Solicitud).WithMany(p => p.AprobacionVacaciones)
                .HasForeignKey(d => d.SolicitudId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AprobacionVacaciones_Solicitud");
        });

        modelBuilder.Entity<Asistencias>(entity =>
        {
            entity.HasKey(e => e.IdAsistencia).HasName("PK__Asistenc__3956DEE616ABC635");

            entity.HasOne(d => d.Empleado).WithMany(p => p.Asistencias)
                .HasForeignKey(d => d.EmpleadoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Asistencias_Empleados");
        });

        modelBuilder.Entity<Bonificaciones>(entity =>
        {
            entity.HasKey(e => e.IdBonificacion).HasName("PK__Bonifica__A8DA9A24C0DF02EE");

            entity.Property(e => e.Descripcion).HasMaxLength(255);
            entity.Property(e => e.Fecha).HasDefaultValueSql("(CONVERT([date],sysdatetime()))");
            entity.Property(e => e.Monto).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.Tipo)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Empleado).WithMany(p => p.Bonificaciones)
                .HasForeignKey(d => d.EmpleadoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Bonificaciones_Empleados");
        });

        modelBuilder.Entity<Contratos>(entity =>
        {
            entity.HasKey(e => e.IdContrato).HasName("PK__Contrato__8569F05A19F229A3");

            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Salario).HasColumnType("decimal(12, 2)");

            entity.HasOne(d => d.Empleado).WithMany(p => p.Contratos)
                .HasForeignKey(d => d.EmpleadoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Contratos_Empleados");

            entity.HasOne(d => d.Tipo).WithMany(p => p.Contratos)
                .HasForeignKey(d => d.TipoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Contratos_ContratosTipo");
        });

        modelBuilder.Entity<ContratosTipo>(entity =>
        {
            entity.HasKey(e => e.IdTipo).HasName("PK__Contrato__9E3A29A574EFEDD4");

            entity.Property(e => e.Jornada)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Descuentos>(entity =>
        {
            entity.HasKey(e => e.IdDescuento).HasName("PK__Descuent__1BD9CB1BF6490798");

            entity.Property(e => e.Descripcion).HasMaxLength(255);
            entity.Property(e => e.Fecha).HasDefaultValueSql("(CONVERT([date],sysdatetime()))");
            entity.Property(e => e.Monto).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.Tipo)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Empleado).WithMany(p => p.Descuentos)
                .HasForeignKey(d => d.EmpleadoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Descuentos_Empleados");
        });

        modelBuilder.Entity<Empleados>(entity =>
        {
            entity.HasKey(e => e.IdEmpleado).HasName("PK__Empleado__CE6D8B9E042CAE50");

            entity.HasIndex(e => e.Cedula, "UQ_Empleados_Cedula").IsUnique();

            entity.Property(e => e.Apellidos)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Cedula)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Correo)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Estado).HasDefaultValue(true);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Genero)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Nombres)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Telefono).HasMaxLength(20);

            entity.HasOne(d => d.Puesto).WithMany(p => p.Empleados)
                .HasForeignKey(d => d.PuestoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Empleados_Puestos");
        });

        modelBuilder.Entity<EmpleadosVacacionesTotales>(entity =>
        {
            entity.HasKey(e => e.EmpleadoId).HasName("PK__Empleado__958BE91035511385");

            entity.Property(e => e.EmpleadoId).ValueGeneratedNever();
            entity.Property(e => e.DiasOtorgados).HasDefaultValue(15);

            entity.HasOne(d => d.Empleado).WithOne(p => p.EmpleadosVacacionesTotales)
                .HasForeignKey<EmpleadosVacacionesTotales>(d => d.EmpleadoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VacTotales_Empleados");
        });

        modelBuilder.Entity<Inasistencias>(entity =>
        {
            entity.HasKey(e => e.IdInasistencia).HasName("PK__Inasiste__72A13AB0C738443C");

            entity.HasOne(d => d.Empleado).WithMany(p => p.Inasistencias)
                .HasForeignKey(d => d.EmpleadoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Inasistencias_Empleados");

            entity.HasOne(d => d.Licencia).WithMany(p => p.Inasistencias)
                .HasForeignKey(d => d.LicenciaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Inasistencias_Licencias");
        });

        modelBuilder.Entity<Licencias>(entity =>
        {
            entity.HasKey(e => e.IdLicencia).HasName("PK__Licencia__0F8D118DE6C88487");

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Nominas>(entity =>
        {
            entity.HasKey(e => e.IdNomina).HasName("PK__Nominas__02F9D722859508C2");

            entity.Property(e => e.Bonificaciones).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.Descuentos).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.FechaEmision).HasDefaultValueSql("(CONVERT([date],sysdatetime()))");
            entity.Property(e => e.SalarioBase).HasColumnType("decimal(12, 2)");

            entity.HasOne(d => d.Empleado).WithMany(p => p.Nominas)
                .HasForeignKey(d => d.EmpleadoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Nominas_Empleados");
        });

        modelBuilder.Entity<Parametros>(entity =>
        {
            entity.HasKey(e => e.IdParametro).HasName("PK__Parametr__37B016F464EB9199");

            entity.HasIndex(e => e.Clave, "UQ__Parametr__E8181E11AB363782").IsUnique();

            entity.Property(e => e.Clave)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Descripcion).HasMaxLength(255);
            entity.Property(e => e.Valor)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<Puestos>(entity =>
        {
            entity.HasKey(e => e.IdPuesto).HasName("PK__Puestos__ADAC6B9C7B3F4FF1");

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.SalarioBase).HasColumnType("decimal(12, 2)");
        });

        modelBuilder.Entity<SolicitudVacaciones>(entity =>
        {
            entity.HasKey(e => e.IdSolicitud).HasName("PK__Solicitu__36899CEFDF98A248");

            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Pendiente");
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.Empleado).WithMany(p => p.SolicitudVacaciones)
                .HasForeignKey(d => d.EmpleadoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SolicitudVacaciones_Empleados");
        });

        modelBuilder.Entity<Usuarios>(entity =>
        {
            entity.HasKey(e => e.IdUsuario).HasName("PK__Usuarios__5B65BF97F7C12E77");

            entity.Property(e => e.Cedula)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.Contraseña)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.FechaRegistro).HasColumnType("datetime");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Rol)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}